spring:
  application:
    name: billingsoftware
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/billing_app
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /api/v1.0
  port: 9000

aws:
  region: eu-north-1
  s3:
    bucket: billing-app-s3-images

jwt:
  secret=${JWT_SECRET_KEY}


